### ISSUE TITLE
[ASK]时间管理, 管理什么?

### ISSUE THREAD

**Issue by leilayanhui** [kiaorahao/AA003BP#1]
# 时间管理, 管理什么?

观察员前来提问, 其实很多都没搞明白, 那就从最近的说起.

根据 ch6 构建自己论证的四个步骤, 一是限定讨论边界. 那我们是否要限定时间管理的讨论边界?

- 时间管理, 管理什么?
    + 管理时间? 时间是可以管理的吗?
    + 管理行为? 那和时间有什么关系?
    + ......
- 时间管理的目的是什么?
    + 提高效率
    + 不再拖延
    + 做规划
    + ....

感觉是从时间角度看一个人的行为, 思想等, 那么能看到什么? 怎么看?

抛砖引玉

**Comment by hujieying** [comment]
* 限定关注人群：  
首先，我觉得我们应该重点关注的是毕业后的社会人。
学生时代不需要考虑如何选择自己的时间节拍，社会已经为你安排好了。但毕业工作后，社会钟允许你拥有自己的时间节拍，你可以自由安排自己的时间，这个时候需要平衡工作、家庭、个人学习等方面的时间。
其次，讨论的人群是仅中国人还是所有？这个待讨论确定

* 时间管理的目的：
“将有限的时间、精力加以分配，以争取最高的效率。”  

* 时间管理到底在管理些什么？（我自己虽然知道时间管理这么个概念，但从没有深入探索和实践过，所以仅以现在搜集到的信息尝试罗列，可能有错漏，欢迎拍砖）
**时间**：4代时间管理
第一代：普遍使用便条和办事清单，明确生活中的各种需要。没有提到有限顺序的概念。  
第二代：使用日历或日程表来安排约会的进度计划，反映需要提交计划的时间并预先安排未来的活动。使用这个管理的人有一定的自我控制能力，但没有按照重要性对任务进行排序，缺少成就感，因为时间总是被日程表所左右。
第三代：注重确定长期、中期及短期目标，然后再根据价值观合理的安排精力和时间，这种理论提倡对每一天进行合理规划，制定一个明确的计划来完成最重要的目标和任务。虽然这种时间管理方法有了很大进步，但是人们发现这种对时间“高效率”分配和使用通常达不到预期的目标，限制了我们的视野，让我们只注重每天的计划。有很多人不再使用这种细致入微，让人备感拘束的时间管理计划和日常安排，而重新起用第一代和第二代管理时间的技巧。
第四代：关注的重点不应该是如何管理时间，而是如何有效的管理自己。人们的满足感通常来源于期望与期望的满足，而这些都是在我们影响圈范围内。第四代时间管理方法注重的不再是具体的事务和时间分配，而是如何维持产出和产能之间的平衡。
**空间**：不同地域，不同文化在时间管理上可能会有偏好？
文化对时间的不同看法会影响时间管理的方式。 例如，线性时间视图是一种将时间以线性方式从一个时刻流向下一个时刻的方法。 这种对时间的线性感知在美国以及大多数北欧国家如德国、瑞士和英国占主导地位。另一种文化时间观是多活动时间观。 在多元文化中，大多数人认为同时完成的活动或任务越多，他们就越快乐。多元活性文化是“多元慢性”的，或者喜欢一次完成多项任务。 在西班牙、葡萄牙和意大利等大多数南欧国家，这种多活动时间观是突出的。   
**变量**：
1.时间管理可能有什么局限呢？
比如第三代时间管理方式可能造成：
①制定过于详细的时间作息表，会对大脑产生欺骗，让大脑产生满足感，以为计划等同于执行，反而极大地削弱了你执行计划的动力；
②每个时间段都安排得死死的，对意志力的消耗会很大，你可能会陷入到深度焦虑和自责当中；
③你很难完全掌控自己一天内的全部时间段，一旦有他人干扰，特别是或领导布置的不可抗拒的任务，整个时间作息表就乱了，你反而不愿意执行剩下的计划了。
2.是不是每个人都能正确找到适合自己的时间管理方式呢？
3.再回到论题上来，找到合适时间管理方式是否就能成为‘精进利器’呢？


* 关于论题有的几个疑问待解决
1.个人感觉时间管理本质上来说应该是正向的有利的，所以镜花水月的定义和是否存在存疑？是否应该将核心点转而关注“精进利器”更加明确-->个人时间管理是否是精进利器，是个人精进利器OR不是个人精进利器
2.精进的定义需要更明确一些？时间管理和精进之间的关系是怎样的？
3.论题讨论人群待确定

一丢丢资料：
* [Time management - Wikipedia](https://en.wikipedia.org/wiki/Time_management)
* [时间管理 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E6%97%B6%E9%97%B4%E7%AE%A1%E7%90%86)
* [时间管理与工作过量　几个值得思考的问题 - BBC 英伦网](https://www.bbc.com/ukchina/simp/vert-cap-45629085)
* [那些“很厉害”的时间管理法，为什么你学不来？ - MBA智库资讯](https://news.mbalib.com/story/244051)
* [《高效人士的七个习惯》 - MBA智库百科](https://wiki.mbalib.com/wiki/%E3%80%8A%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF%E3%80%8B)

**Comment by liuxuyi1** [comment]
一点个人浅见，还请各位指正。

- 皓的时间管理，更多的是在通过细致的记录自己时间的基础上，对自己的时间进行优化调整。这个部分是非常细化的。我看了皓写的招募贴，如果按照我对皓的了解，他的论题，似乎更像是柳比歇夫式的时间管理方法是有效的还是无效的。但因为没有进行细致的限定，所以会造成一些歧义。

- 个人认为并不存在对于时间管理的准确定义，我们无法从学界得到对这个词的精准定义。包括维基百科中的定义，其词条来源也非权威信源。

- 当前的时间管理更像是一个任由知识付费界的打扮的小姑娘，每个所谓的专家都在对其进行不同的定义和理解。很多人都上过时间管理课程，就会对时间管理有着五花八门的理解。这就会导致我们的论题很难找到一个准确的讨论边界。

- 如果按照传统方式，大家开会讨论出一个边界，因为这个话题太过于庞杂，很难找到清晰的边界，即使找出来，在后续的辩论中，某一方也会因为较难论证，从而试图重新框定论点，对论题进行有利于己方的修改，这是在一个陌生领域辩论中，大概率会出现的状况。

- 建议可以借助工具，进行异步辩论，将正反方的辩论和资料的收集同步进行，这样在辩论中，逐渐清晰出讨论的重点和边界，资料收集也更有动力更有方向，即使最后没有达成一致的边界，也会对这个话题有着比较深入的推动，形成一个精彩的论证过程，论证分析的能力得到了很好的锻炼，达成了我们的核心目标。

**Comment by leilayanhui** [comment]
在目前的讨论中, 时间管理应该包括以下行为

- 记录时间
- 分析数据
- 制定目标, 计划
- 分配时间
- 定期复盘


还有什么吗, 欢迎补充

**Comment by kiaorahao** [comment]
可以看下zwd.007 文章，有详细的描述

**Comment by leilayanhui** [comment]
我写的这些是人们听到 时间管理 时的反应，主要是为了我们正反方能达成个共识。

学术圈也没给出统一的概念，我们的讨论不会就限定在学术论证里吧

**Comment by kiaorahao** [comment]
没有统一概念，不过可以选择对于己方有利的观点和概念展开论辩。找到有利于自己方向的边界是比较关键的。

**Comment by leilayanhui** [comment]
你辩你的，我找点你论据里的漏洞。我辩我的，你找点我论据里的漏洞，这样？

这样的辩论感觉说的都不是同一件事…

**Comment by kiaorahao** [comment]
极端情况肯定是越对自己有利的claim越好，所以得讨价还价，找到一个双方都可以接受的大claim，再开始分道扬镳，各自做功课使劲整。：）

**Comment by kiaorahao** [comment]
@黎黎教练建议：
>这个问题，我可以回答一下。构建自己的论证时，限制边界，可以理解为维护自己结论的论证力量，加了约束，才有可能让结论更加可信。这个边界构成了你的立论点。当然这里可能会被反方所攻击，如果对方看出了薄弱之处。并不一定是论据层面的。并且反方还可以从你整个推理过程的环节，进行驳斥。
